//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FfkApi.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesException() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FfkApi.Exceptions.ResourceMessagesException", typeof(ResourceMessagesException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anexo não encontrado.
        /// </summary>
        public static string ANEXO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("ANEXO_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O AppId não é válido.
        /// </summary>
        public static string APP_ID_INVALIDO {
            get {
                return ResourceManager.GetString("APP_ID_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um sistema cliente cadastrado com este AppId.
        /// </summary>
        public static string APP_ID_JA_EXISTE {
            get {
                return ResourceManager.GetString("APP_ID_JA_EXISTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppId ou senha inválidos.
        /// </summary>
        public static string APP_ID_OU_SENHA_INVALIDOS {
            get {
                return ResourceManager.GetString("APP_ID_OU_SENHA_INVALIDOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O AppId não pode ser vazio.
        /// </summary>
        public static string APP_ID_VAZIO {
            get {
                return ResourceManager.GetString("APP_ID_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviço de armazenamento de arquivos disponível.
        /// </summary>
        public static string ARMAZENADOR_DE_ARQUIVOS_DISPONIVEL {
            get {
                return ResourceManager.GetString("ARMAZENADOR_DE_ARQUIVOS_DISPONIVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviço de armazenamento de arquivos indisponível.
        /// </summary>
        public static string ARMAZENADOR_DE_ARQUIVOS_INDISPONIVEL {
            get {
                return ResourceManager.GetString("ARMAZENADOR_DE_ARQUIVOS_INDISPONIVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo muito grande. O tamanho máximo é de {tamanho-maximo}.
        /// </summary>
        public static string ARQUIVO_MUITO_GRANDE {
            get {
                return ResourceManager.GetString("ARQUIVO_MUITO_GRANDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O arquivo não pode ser vazio.
        /// </summary>
        public static string ARQUIVO_VAZIO {
            get {
                return ResourceManager.GetString("ARQUIVO_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é permitido excluir a si mesmo.
        /// </summary>
        public static string AUTO_EXCLUSAO {
            get {
                return ResourceManager.GetString("AUTO_EXCLUSAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O código não pode estar vazio.
        /// </summary>
        public static string CODIGO_VAZIO {
            get {
                return ResourceManager.GetString("CODIGO_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Cpf não é válido.
        /// </summary>
        public static string CPF_INVALIDO {
            get {
                return ResourceManager.GetString("CPF_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um usuário cadastrado com este Cpf.
        /// </summary>
        public static string CPF_JA_EXISTE {
            get {
                return ResourceManager.GetString("CPF_JA_EXISTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Cpf não pode estar vazio.
        /// </summary>
        public static string CPF_VAZIO {
            get {
                return ResourceManager.GetString("CPF_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados inválidos.
        /// </summary>
        public static string DADOS_INVALIDOS {
            get {
                return ResourceManager.GetString("DADOS_INVALIDOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de expiração deve ser no formato dd/mm/aaaa.
        /// </summary>
        public static string DATA_EXPIRACAO_INVALIDA {
            get {
                return ResourceManager.GetString("DATA_EXPIRACAO_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data final deve ser no formato dd/mm/aaaa.
        /// </summary>
        public static string DATA_FINAL_INVALIDA {
            get {
                return ResourceManager.GetString("DATA_FINAL_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data final deve ser maior ou igual a data inicial.
        /// </summary>
        public static string DATA_FINAL_MENOR_QUE_DATA_INICIAL {
            get {
                return ResourceManager.GetString("DATA_FINAL_MENOR_QUE_DATA_INICIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data final não pode ser vazia.
        /// </summary>
        public static string DATA_FINAL_VAZIA {
            get {
                return ResourceManager.GetString("DATA_FINAL_VAZIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data inicial deve ser no formato dd/mm/aaaa.
        /// </summary>
        public static string DATA_INICIAL_INVALIDA {
            get {
                return ResourceManager.GetString("DATA_INICIAL_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data inicial não pode ser vazia.
        /// </summary>
        public static string DATA_INICIAL_VAZIA {
            get {
                return ResourceManager.GetString("DATA_INICIAL_VAZIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição não pode estar vazia.
        /// </summary>
        public static string DESCRICAO_VAZIA {
            get {
                return ResourceManager.GetString("DESCRICAO_VAZIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail de ativação só pode ser enviado para usuários inativos.
        /// </summary>
        public static string EMAIL_ATIVACAO_SOMENTE_USUARIOS_INATIVOS {
            get {
                return ResourceManager.GetString("EMAIL_ATIVACAO_SOMENTE_USUARIOS_INATIVOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail não é válido.
        /// </summary>
        public static string EMAIL_INVALIDO {
            get {
                return ResourceManager.GetString("EMAIL_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um usuário cadastrado com este e-mail.
        /// </summary>
        public static string EMAIL_JA_EXISTE {
            get {
                return ResourceManager.GetString("EMAIL_JA_EXISTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existem e-mails de membros da equipe repetidos.
        /// </summary>
        public static string EMAIL_MEMBRO_EQUIPE_REPETIDOS {
            get {
                return ResourceManager.GetString("EMAIL_MEMBRO_EQUIPE_REPETIDOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail do membro da equipe não pode estar vazio.
        /// </summary>
        public static string EMAIL_MEMBRO_EQUIPE_VAZIO {
            get {
                return ResourceManager.GetString("EMAIL_MEMBRO_EQUIPE_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail de nova senha só pode ser enviado para usuários ativos.
        /// </summary>
        public static string EMAIL_NOVA_SENHA_SOMENTE_USUARIOS_ATIVOS {
            get {
                return ResourceManager.GetString("EMAIL_NOVA_SENHA_SOMENTE_USUARIOS_ATIVOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail ou senha inválidos.
        /// </summary>
        public static string EMAIL_OU_SENHA_INVALIDOS {
            get {
                return ResourceManager.GetString("EMAIL_OU_SENHA_INVALIDOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail de usuário &apos;{email}&apos; não encontrado.
        /// </summary>
        public static string EMAIL_USUARIO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("EMAIL_USUARIO_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail de usuário não pode ser vazio.
        /// </summary>
        public static string EMAIL_USUARIO_VAZIO {
            get {
                return ResourceManager.GetString("EMAIL_USUARIO_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail não pode estar vazio.
        /// </summary>
        public static string EMAIL_VAZIO {
            get {
                return ResourceManager.GetString("EMAIL_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emails de usuarios não encontrados: {lista}.
        /// </summary>
        public static string EMAILS_DE_USUARIOS_NAO_ENCONTRADOS {
            get {
                return ResourceManager.GetString("EMAILS_DE_USUARIOS_NAO_ENCONTRADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviço de envio de e-mail disponível.
        /// </summary>
        public static string ENVIAR_EMAIL_DISPONIVEL {
            get {
                return ResourceManager.GetString("ENVIAR_EMAIL_DISPONIVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviço de envio de e-mail indisponível.
        /// </summary>
        public static string ENVIAR_EMAIL_INDISPONIVEL {
            get {
                return ResourceManager.GetString("ENVIAR_EMAIL_INDISPONIVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipe não encontrada.
        /// </summary>
        public static string EQUIPE_NAO_ENCONTRADA {
            get {
                return ResourceManager.GetString("EQUIPE_NAO_ENCONTRADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro desconhecido.
        /// </summary>
        public static string ERRO_DESCONHECIDO {
            get {
                return ResourceManager.GetString("ERRO_DESCONHECIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed não encontrado.
        /// </summary>
        public static string FEED_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("FEED_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID não é válido.
        /// </summary>
        public static string ID_INVALIDO {
            get {
                return ResourceManager.GetString("ID_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID não pode ser vazio.
        /// </summary>
        public static string ID_VAZIO {
            get {
                return ResourceManager.GetString("ID_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível trocar a organização da equipe enquanto existirem membros associados.
        /// </summary>
        public static string IMPOSSIVEL_TROCAR_ORGANIZACAO_EQUIPE_QUANDO_TEM_MEMBROS {
            get {
                return ResourceManager.GetString("IMPOSSIVEL_TROCAR_ORGANIZACAO_EQUIPE_QUANDO_TEM_MEMBROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indisponibilidade não encontrada.
        /// </summary>
        public static string INDISPONIBILIDADE_NAO_ENCONTRADA {
            get {
                return ResourceManager.GetString("INDISPONIBILIDADE_NAO_ENCONTRADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As datas estão conflitando com outra indisponibilidade já cadastrada para este usuário.
        /// </summary>
        public static string JA_EXISTE_INDISPONIBILIDADE_NO_PERIODO {
            get {
                return ResourceManager.GetString("JA_EXISTE_INDISPONIBILIDADE_NO_PERIODO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A indicação de líder deve ser true ou false.
        /// </summary>
        public static string LIDER_NULL {
            get {
                return ResourceManager.GetString("LIDER_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limite de requisições excedido. Tente novamente em instantes..
        /// </summary>
        public static string LIMITE_REQUISICOES_EXCEDIDO {
            get {
                return ResourceManager.GetString("LIMITE_REQUISICOES_EXCEDIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A lista de Feeds não pode ser vazia.
        /// </summary>
        public static string LISTA_DE_FEED_VAZIA {
            get {
                return ResourceManager.GetString("LISTA_DE_FEED_VAZIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A lista de organizações não pode ser vazia.
        /// </summary>
        public static string LISTA_DE_ORGANIZACAO_VAZIA {
            get {
                return ResourceManager.GetString("LISTA_DE_ORGANIZACAO_VAZIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O membro da equipe não pode ser vazio.
        /// </summary>
        public static string MEMBRO_EQUIPE_NULL {
            get {
                return ResourceManager.GetString("MEMBRO_EQUIPE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviço de mensageria disponível..
        /// </summary>
        public static string MENSAGERIA_DISPONIVEL {
            get {
                return ResourceManager.GetString("MENSAGERIA_DISPONIVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviço de mensageria indisponível..
        /// </summary>
        public static string MENSAGERIA_INDISPONIVEL {
            get {
                return ResourceManager.GetString("MENSAGERIA_INDISPONIVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma alteração para ser salva.
        /// </summary>
        public static string NENHUMA_ALTERACAO {
            get {
                return ResourceManager.GetString("NENHUMA_ALTERACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe uma equipe cadastrada com este nome nesta organização.
        /// </summary>
        public static string NOME_DE_EQUIPE_JA_EXISTE_NA_ORGANIZACAO {
            get {
                return ResourceManager.GetString("NOME_DE_EQUIPE_JA_EXISTE_NA_ORGANIZACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe uma organização cadastrada com este nome.
        /// </summary>
        public static string NOME_DE_ORGANIZACAO_JA_EXISTE {
            get {
                return ResourceManager.GetString("NOME_DE_ORGANIZACAO_JA_EXISTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome de organização repetido na lista.
        /// </summary>
        public static string NOME_DE_ORGANIZACAO_REPETIDO {
            get {
                return ResourceManager.GetString("NOME_DE_ORGANIZACAO_REPETIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome de equipe &apos;{nome-equipe}&apos; não encontrado.
        /// </summary>
        public static string NOME_EQUIPE_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("NOME_EQUIPE_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome da equipe não pode ser vazio.
        /// </summary>
        public static string NOME_EQUIPE_VAZIA {
            get {
                return ResourceManager.GetString("NOME_EQUIPE_VAZIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome não pode estar vazio.
        /// </summary>
        public static string NOME_VAZIO {
            get {
                return ResourceManager.GetString("NOME_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nomes de equipes não encontrados: {lista}.
        /// </summary>
        public static string NOMES_DE_EQUIPES_NAO_ENCONTRADOS {
            get {
                return ResourceManager.GetString("NOMES_DE_EQUIPES_NAO_ENCONTRADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A organização já está vinculada a outras entidades do sistema e não pode ser excluída.
        /// </summary>
        public static string ORGANIZACAO_JA_VINCULADA {
            get {
                return ResourceManager.GetString("ORGANIZACAO_JA_VINCULADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organização não encontrada.
        /// </summary>
        public static string ORGANIZACAO_NAO_ENCONTRADA {
            get {
                return ResourceManager.GetString("ORGANIZACAO_NAO_ENCONTRADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A organização não pode estar vazia.
        /// </summary>
        public static string ORGANIZACAO_VAZIA {
            get {
                return ResourceManager.GetString("ORGANIZACAO_VAZIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O perfil de acesso não pode ser vazio.
        /// </summary>
        public static string PERFIL_ACESSO_VAZIO {
            get {
                return ResourceManager.GetString("PERFIL_ACESSO_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfis de acesso não encontrados: {lista}.
        /// </summary>
        public static string PERFIS_ACESSO_NAO_ENCONTRADOS {
            get {
                return ResourceManager.GetString("PERFIS_ACESSO_NAO_ENCONTRADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A permissão não pode ser vazia.
        /// </summary>
        public static string PERMISSAO_VAZIA {
            get {
                return ResourceManager.GetString("PERMISSAO_VAZIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissões não encontradas: {lista}.
        /// </summary>
        public static string PERMISSOES_NAO_ENCONTRADAS {
            get {
                return ResourceManager.GetString("PERMISSOES_NAO_ENCONTRADAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O refresh token não pode estar vazio.
        /// </summary>
        public static string REFRESH_TOKEN_VAZIO {
            get {
                return ResourceManager.GetString("REFRESH_TOKEN_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário ter a permissão &apos;{permissao}&apos; para esta operação.
        /// </summary>
        public static string SEM_PERMISSAO {
            get {
                return ResourceManager.GetString("SEM_PERMISSAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você não tem permissão de alterar a organização.
        /// </summary>
        public static string SEM_PERMISSAO_ALTERAR_ORGANIZACAO {
            get {
                return ResourceManager.GetString("SEM_PERMISSAO_ALTERAR_ORGANIZACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum token encontrado na requisição.
        /// </summary>
        public static string SEM_TOKEN {
            get {
                return ResourceManager.GetString("SEM_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha informada está diferente da senha atual.
        /// </summary>
        public static string SENHA_ANTIGA_DIFERENTE_DA_SENHA_INFORMADA {
            get {
                return ResourceManager.GetString("SENHA_ANTIGA_DIFERENTE_DA_SENHA_INFORMADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha não pode ser vazia, deve ter no mínimo 8 caracteres, deve conter pelo menos uma letra maiúscula, uma letra minúscula, um número e um símbolo.
        /// </summary>
        public static string SENHA_INVALIDA {
            get {
                return ResourceManager.GetString("SENHA_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha não pode estar vazia.
        /// </summary>
        public static string SENHA_VAZIA {
            get {
                return ResourceManager.GetString("SENHA_VAZIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessão expirada.
        /// </summary>
        public static string SESSAO_EXPIRADA {
            get {
                return ResourceManager.GetString("SESSAO_EXPIRADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessão inválida.
        /// </summary>
        public static string SESSAO_INVALIDA {
            get {
                return ResourceManager.GetString("SESSAO_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema cliente não encontrado.
        /// </summary>
        public static string SISTEMACLIENTE_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("SISTEMACLIENTE_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organização inválida. Somente usuários com perfil de Administrador podem cadastrar, alterar ou pesquisar atos de outra organização.
        /// </summary>
        public static string SO_ADM_PODE_CRUD_ATOS_PARA_OUTRA_ORGANIZACAO {
            get {
                return ResourceManager.GetString("SO_ADM_PODE_CRUD_ATOS_PARA_OUTRA_ORGANIZACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário ser administrador do sistema para acessar este recurso.
        /// </summary>
        public static string SOMENTE_ADMINISTRADOR {
            get {
                return ResourceManager.GetString("SOMENTE_ADMINISTRADOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apenas um arquivo é permitido.
        /// </summary>
        public static string SOMENTE_UM_ARQUIVO {
            get {
                return ResourceManager.GetString("SOMENTE_UM_ARQUIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status inválido. Valores possíveis: {ValoresPossiveis}.
        /// </summary>
        public static string STATUS_INVALIDO {
            get {
                return ResourceManager.GetString("STATUS_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O status não pode estar vazio.
        /// </summary>
        public static string STATUS_VAZIO {
            get {
                return ResourceManager.GetString("STATUS_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O telefone não é válido.
        /// </summary>
        public static string TELEFONE_INVALIDO {
            get {
                return ResourceManager.GetString("TELEFONE_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token de aplicação ausente.
        /// </summary>
        public static string TOKEN_APLICACAO_AUSENTE {
            get {
                return ResourceManager.GetString("TOKEN_APLICACAO_AUSENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token de aplicação inválido.
        /// </summary>
        public static string TOKEN_APLICACAO_INVALIDO {
            get {
                return ResourceManager.GetString("TOKEN_APLICACAO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token de ativação expirado. Entre em contato com o administrador do sistema e solicite um novo token..
        /// </summary>
        public static string TOKEN_ATIVACAO_EXPIRADO {
            get {
                return ResourceManager.GetString("TOKEN_ATIVACAO_EXPIRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token de ativação não encontrado.
        /// </summary>
        public static string TOKEN_ATIVACAO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("TOKEN_ATIVACAO_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O token de ativação não pode estar vazio.
        /// </summary>
        public static string TOKEN_ATIVACAO_VAZIO {
            get {
                return ResourceManager.GetString("TOKEN_ATIVACAO_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token expirado.
        /// </summary>
        public static string TOKEN_EXPIRADO {
            get {
                return ResourceManager.GetString("TOKEN_EXPIRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token inválido.
        /// </summary>
        public static string TOKEN_INVALIDO {
            get {
                return ResourceManager.GetString("TOKEN_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token de senha expirado. Entre em contato com o administrador do sistema e solicite um novo token..
        /// </summary>
        public static string TOKEN_NOVA_SENHA_EXPIRADO {
            get {
                return ResourceManager.GetString("TOKEN_NOVA_SENHA_EXPIRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token de senha não encontrado.
        /// </summary>
        public static string TOKEN_NOVA_SENHA_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("TOKEN_NOVA_SENHA_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O token de nova senha não pode estar vazio.
        /// </summary>
        public static string TOKEN_NOVA_SENHA_VAZIO {
            get {
                return ResourceManager.GetString("TOKEN_NOVA_SENHA_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário já está com status de excluído.
        /// </summary>
        public static string USUARIO_JA_EXCLUIDO {
            get {
                return ResourceManager.GetString("USUARIO_JA_EXCLUIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario não encontrado.
        /// </summary>
        public static string USUARIO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("USUARIO_NAO_ENCONTRADO", resourceCulture);
            }
        }
    }
}
