// <auto-generated />
using System;
using FfkApi.Infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FfkApi.Infrastructure.Migrations
{
    [DbContext(typeof(FfkApiDbContext))]
    partial class FfkApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FeedsAnexos", b =>
                {
                    b.Property<Guid>("IdFeed")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdAnexo")
                        .HasColumnType("uuid");

                    b.HasKey("IdFeed", "IdAnexo")
                        .HasName("PK_FeedsAnexos");

                    b.HasIndex("IdAnexo");

                    b.ToTable("FeedsAnexos");
                });

            modelBuilder.Entity("FeedsEquipes", b =>
                {
                    b.Property<Guid>("IdFeed")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdEquipe")
                        .HasColumnType("uuid");

                    b.HasKey("IdFeed", "IdEquipe")
                        .HasName("PK_FeedsEquipes");

                    b.HasIndex("IdEquipe");

                    b.ToTable("FeedsEquipes");
                });

            modelBuilder.Entity("FeedsUsuarios", b =>
                {
                    b.Property<Guid>("IdFeed")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.HasKey("IdFeed", "IdUsuario")
                        .HasName("PK_FeedsUsuarios");

                    b.HasIndex("IdUsuario");

                    b.ToTable("FeedsUsuarios");
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.Anexo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Extensao")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("MimeType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NomeArquivoArmazenamento")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("TamanhoBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<string>("Texto")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PK_Anexos");

                    b.ToTable("Anexos", (string)null);
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.AuditoriaSeguranca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Caminho")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Detalhes")
                        .HasColumnType("text");

                    b.Property<string>("EnderecoIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("Evento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Metodo")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Usuario")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id")
                        .HasName("PK_AuditoriasSeguranca");

                    b.ToTable("AuditoriasSeguranca", (string)null);
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.Checklist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("IdOrganizacao")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id")
                        .HasName("PK_Checklists");

                    b.HasIndex("IdOrganizacao")
                        .HasDatabaseName("IX_Checklists_IdOrganizacao");

                    b.ToTable("Checklists", (string)null);
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.ChecklistGatilhoRespostaPossivel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("IdChecklistItem")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdChecklistRespostaPossivel")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_ChecklistGatilhoRespostaPossivel");

                    b.HasIndex("IdChecklistItem")
                        .HasDatabaseName("IX_ChecklistGatilhosRespostasPossiveis_IdChecklistItem");

                    b.HasIndex("IdChecklistRespostaPossivel")
                        .HasDatabaseName("IX_ChecklistGatilhosRespostasPossiveis_IdChecklistRespostaPossivel");

                    b.ToTable("ChecklistGatilhosRespostasPossiveis", (string)null);
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.ChecklistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("IdChecklist")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdDependeDeChecklistItem")
                        .HasColumnType("uuid");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<string>("TipoChecklistItem")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id")
                        .HasName("PK_ChecklistItem");

                    b.HasIndex("IdChecklist")
                        .HasDatabaseName("IX_ChecklistItens_IdChecklist");

                    b.HasIndex("IdDependeDeChecklistItem")
                        .HasDatabaseName("IX_ChecklistItens_IdDependeDeChecklistItem");

                    b.ToTable("ChecklistItens", (string)null);
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.ChecklistPreenchido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("timestamptz");

                    b.Property<string>("DescricaoChecklist")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("IdChecklist")
                        .HasColumnType("uuid");

                    b.Property<string>("NomeChecklist")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id")
                        .HasName("PK_ChecklistsPreenchidos");

                    b.HasIndex("IdChecklist")
                        .HasDatabaseName("IX_ChecklistsPreenchidos_IdChecklist");

                    b.ToTable("ChecklistsPreenchidos", (string)null);
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.ChecklistPreenchidoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("timestamptz");

                    b.Property<string>("DescricaoItem")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DescricaoRespostaEscolhida")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("GeraInconformidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("IdChecklistPreenchido")
                        .HasColumnType("uuid");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("OrdemItem")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_ChecklistPreenchidoItem");

                    b.HasIndex("IdChecklistPreenchido")
                        .HasDatabaseName("IX_ChecklistPreenchidoItens_IdChecklistPreenchido");

                    b.ToTable("ChecklistPreenchidoItens", (string)null);
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.ChecklistRespostaPossivel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("GeraInconformidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("IdChecklistItem")
                        .HasColumnType("uuid");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_ChecklistRespostaPossivel");

                    b.HasIndex("IdChecklistItem")
                        .HasDatabaseName("IX_ChecklistRespostasPossiveis_IdChecklistItem");

                    b.ToTable("ChecklistRespostasPossiveis", (string)null);
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.Equipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("IdOrganizacao")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id")
                        .HasName("PK_Equipes");

                    b.HasIndex("IdOrganizacao")
                        .HasDatabaseName("IX_Equipes_IdOrganizacao");

                    b.HasIndex("Nome", "IdOrganizacao")
                        .IsUnique()
                        .HasDatabaseName("UK_Equipes_Nome_IdOrganizacao");

                    b.ToTable("Equipes", (string)null);
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.Feed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateOnly?>("ExpiraEm")
                        .HasColumnType("date");

                    b.Property<Guid>("IdOrganizacao")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PalavrasChave")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id")
                        .HasName("PK_Feeds");

                    b.HasIndex("IdOrganizacao")
                        .HasDatabaseName("IX_Feeds_IdOrganizacao");

                    b.ToTable("Feeds", (string)null);
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.Fila", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("IdEquipe")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdUsuario")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_Filas");

                    b.HasIndex("IdEquipe")
                        .IsUnique()
                        .HasDatabaseName("IX_Filas_IdEquipe");

                    b.HasIndex("IdUsuario")
                        .IsUnique()
                        .HasDatabaseName("IX_Filas_IdUsuario");

                    b.ToTable("Filas", (string)null);
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.FilaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("IdFila")
                        .HasColumnType("uuid");

                    b.Property<long>("Posicao")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK_FilaItens");

                    b.HasIndex("IdFila")
                        .HasDatabaseName("IX_FilaItens_IdFila");

                    b.ToTable("FilaItens", (string)null);
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.Indisponibilidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("timestamptz");

                    b.Property<DateOnly>("DataFinal")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataInicial")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_Indisponibilidades");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("IX_Indisponibilidades_IdUsuario");

                    b.ToTable("Indisponibilidades", (string)null);
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.MembroEquipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("IdEquipe")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<bool>("Lider")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id")
                        .HasName("PK_MembrosEquipe");

                    b.HasIndex("IdEquipe")
                        .HasDatabaseName("IX_MembrosEquipe_IdEquipe");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("IX_MembrosEquipe_IdUsuario");

                    b.HasIndex("IdEquipe", "IdUsuario")
                        .IsUnique()
                        .HasDatabaseName("UK_MembrosEquipe_IdEquipe_IdUsuario");

                    b.ToTable("MembrosEquipe", (string)null);
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.Organizacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ModeloEmailAtivacao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ModeloEmailNovaSenha")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RemetenteEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RemetenteNome")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id")
                        .HasName("PK_Organizacoes");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("UK_Organizacoes_Nome");

                    b.ToTable("Organizacoes", (string)null);
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.PerfilAcesso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id")
                        .HasName("PK_PerfisAcesso");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("UK_PerfisAcesso_Nome");

                    b.ToTable("PerfisAcesso", (string)null);
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.Permissao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id")
                        .HasName("PK_Permissoes");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("UK_Permissoes_Nome");

                    b.ToTable("Permissoes", (string)null);
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("IdOrganizacao")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TipoPessoa")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id")
                        .HasName("PK_Pessoa");

                    b.HasIndex("IdOrganizacao")
                        .HasDatabaseName("IX_Pessoas_IdOrganizacao");

                    b.ToTable("Pessoas", (string)null);
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id")
                        .HasName("PK_RefreshTokens");

                    b.HasAlternateKey("IdUsuario")
                        .HasName("UK_RefreshTokens_IdUsuario");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.SistemaCliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Senha")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id")
                        .HasName("PK_SistemasCliente");

                    b.HasIndex("AppId")
                        .IsUnique()
                        .HasDatabaseName("UK_SistemasCliente_AppId");

                    b.ToTable("SistemasCliente", (string)null);
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.TokenAtivacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("BaseExpiracaoUtc")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("EmailEnviado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ErroEnvioEmail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UltimaTentativaEnvioEmail")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id")
                        .HasName("PK_TokensAtivacao");

                    b.HasAlternateKey("IdUsuario")
                        .HasName("UK_TokensAtivacao_IdUsuario");

                    b.ToTable("TokensAtivacao", (string)null);
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.TokenNovaSenha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("EmailEnviado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ErroEnvioEmail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UltimaTentativaEnvioEmail")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id")
                        .HasName("PK_TokensNovaSenha");

                    b.HasAlternateKey("IdUsuario")
                        .HasName("UK_TokensNovaSenha_IdUsuario");

                    b.ToTable("TokensNovaSenha", (string)null);
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("IdOrganizacao")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Senha")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id")
                        .HasName("PK_Usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UK_Usuarios_Email");

                    b.HasIndex("IdOrganizacao")
                        .HasDatabaseName("IX_Usuarios_IdOrganizacao");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("PerfisAcessoPermissoes", b =>
                {
                    b.Property<Guid>("IdPerfilAcesso")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdPermissao")
                        .HasColumnType("uuid");

                    b.HasKey("IdPerfilAcesso", "IdPermissao")
                        .HasName("PK_PerfisAcessoPermissoes");

                    b.HasIndex("IdPermissao");

                    b.ToTable("PerfisAcessoPermissoes");
                });

            modelBuilder.Entity("UsuariosPerfisAcesso", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdPerfilAcesso")
                        .HasColumnType("uuid");

                    b.HasKey("IdUsuario", "IdPerfilAcesso")
                        .HasName("PK_UsuariosPerfisAcesso");

                    b.HasIndex("IdPerfilAcesso");

                    b.ToTable("UsuariosPerfisAcesso");
                });

            modelBuilder.Entity("UsuariosPermissoes", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdPermissao")
                        .HasColumnType("uuid");

                    b.HasKey("IdUsuario", "IdPermissao")
                        .HasName("PK_UsuariosPermissoes");

                    b.HasIndex("IdPermissao");

                    b.ToTable("UsuariosPermissoes");
                });

            modelBuilder.Entity("FeedsAnexos", b =>
                {
                    b.HasOne("FfkApi.Domain.Entities.Anexo", null)
                        .WithMany()
                        .HasForeignKey("IdAnexo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FeedsAnexos_Ref_Anexos");

                    b.HasOne("FfkApi.Domain.Entities.Feed", null)
                        .WithMany()
                        .HasForeignKey("IdFeed")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FeedsAnexos_Ref_Feeds");
                });

            modelBuilder.Entity("FeedsEquipes", b =>
                {
                    b.HasOne("FfkApi.Domain.Entities.Equipe", null)
                        .WithMany()
                        .HasForeignKey("IdEquipe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FeedsEquipes_Ref_Equipes");

                    b.HasOne("FfkApi.Domain.Entities.Feed", null)
                        .WithMany()
                        .HasForeignKey("IdFeed")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FeedsEquipes_Ref_Feeds");
                });

            modelBuilder.Entity("FeedsUsuarios", b =>
                {
                    b.HasOne("FfkApi.Domain.Entities.Feed", null)
                        .WithMany()
                        .HasForeignKey("IdFeed")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FeedsUsuarios_Ref_Feeds");

                    b.HasOne("FfkApi.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FeedsUsuarios_Ref_Usuarios");
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.Checklist", b =>
                {
                    b.HasOne("FfkApi.Domain.Entities.Organizacao", "Organizacao")
                        .WithMany()
                        .HasForeignKey("IdOrganizacao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Checklists_Ref_Organizacoes");

                    b.Navigation("Organizacao");
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.ChecklistGatilhoRespostaPossivel", b =>
                {
                    b.HasOne("FfkApi.Domain.Entities.ChecklistItem", "ChecklistItem")
                        .WithMany("GatilhosDeResposta")
                        .HasForeignKey("IdChecklistItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ChecklistGatilhosRespostasPossiveis_Ref_ChecklistItens");

                    b.HasOne("FfkApi.Domain.Entities.ChecklistRespostaPossivel", "RespostaGatilho")
                        .WithMany()
                        .HasForeignKey("IdChecklistRespostaPossivel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ChecklistGatilhosRespostasPossiveis_Ref_ChecklistRespostasPossiveis");

                    b.Navigation("ChecklistItem");

                    b.Navigation("RespostaGatilho");
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.ChecklistItem", b =>
                {
                    b.HasOne("FfkApi.Domain.Entities.Checklist", "Checklist")
                        .WithMany("ChecklistItens")
                        .HasForeignKey("IdChecklist")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ChecklistItens_Ref_Checklists");

                    b.HasOne("FfkApi.Domain.Entities.ChecklistItem", "DependeDeChecklistItem")
                        .WithMany()
                        .HasForeignKey("IdDependeDeChecklistItem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ChecklistItens_Ref_ChecklistItens");

                    b.Navigation("Checklist");

                    b.Navigation("DependeDeChecklistItem");
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.ChecklistPreenchido", b =>
                {
                    b.HasOne("FfkApi.Domain.Entities.Checklist", "Checklist")
                        .WithMany()
                        .HasForeignKey("IdChecklist")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("FK_ChecklistsPreenchidos_Ref_Checklists");

                    b.Navigation("Checklist");
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.ChecklistPreenchidoItem", b =>
                {
                    b.HasOne("FfkApi.Domain.Entities.ChecklistPreenchido", "ChecklistPreenchido")
                        .WithMany("ChecklistPreenchidoItens")
                        .HasForeignKey("IdChecklistPreenchido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ChecklistPreenchidoItens_Ref_ChecklistPreenchido");

                    b.Navigation("ChecklistPreenchido");
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.ChecklistRespostaPossivel", b =>
                {
                    b.HasOne("FfkApi.Domain.Entities.ChecklistItem", "ChecklistItem")
                        .WithMany("ChecklistRespostasPossiveis")
                        .HasForeignKey("IdChecklistItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ChecklistRespostasPossiveis_Ref_ChecklistItens");

                    b.Navigation("ChecklistItem");
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.Equipe", b =>
                {
                    b.HasOne("FfkApi.Domain.Entities.Organizacao", "Organizacao")
                        .WithMany()
                        .HasForeignKey("IdOrganizacao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Equipes_Ref_Organizacoes");

                    b.Navigation("Organizacao");
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.Feed", b =>
                {
                    b.HasOne("FfkApi.Domain.Entities.Organizacao", "Organizacao")
                        .WithMany()
                        .HasForeignKey("IdOrganizacao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Feeds_Ref_Organizacoes");

                    b.Navigation("Organizacao");
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.Fila", b =>
                {
                    b.HasOne("FfkApi.Domain.Entities.Equipe", "Equipe")
                        .WithOne("Fila")
                        .HasForeignKey("FfkApi.Domain.Entities.Fila", "IdEquipe")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Filas_Ref_Equipes");

                    b.HasOne("FfkApi.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Fila")
                        .HasForeignKey("FfkApi.Domain.Entities.Fila", "IdUsuario")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Filas_Ref_Usuarios");

                    b.Navigation("Equipe");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.FilaItem", b =>
                {
                    b.HasOne("FfkApi.Domain.Entities.Fila", "Fila")
                        .WithMany("FilaItens")
                        .HasForeignKey("IdFila")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FilaItens_Ref_Filas");

                    b.Navigation("Fila");
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.Indisponibilidade", b =>
                {
                    b.HasOne("FfkApi.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Indisponibilidades_Ref_Usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.MembroEquipe", b =>
                {
                    b.HasOne("FfkApi.Domain.Entities.Equipe", "Equipe")
                        .WithMany("Membros")
                        .HasForeignKey("IdEquipe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MembrosEquipe_Ref_Equipes");

                    b.HasOne("FfkApi.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MembrosEquipe_Ref_Usuarios");

                    b.Navigation("Equipe");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.Pessoa", b =>
                {
                    b.HasOne("FfkApi.Domain.Entities.Organizacao", "Organizacao")
                        .WithMany()
                        .HasForeignKey("IdOrganizacao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Pessoas_Ref_Organizacoes");

                    b.Navigation("Organizacao");
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("FfkApi.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RefreshTokens_Ref_Usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.TokenAtivacao", b =>
                {
                    b.HasOne("FfkApi.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TokensAtivacao_Ref_Usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.TokenNovaSenha", b =>
                {
                    b.HasOne("FfkApi.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TokensNovaSenha_Ref_Usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("FfkApi.Domain.Entities.Organizacao", "Organizacao")
                        .WithMany()
                        .HasForeignKey("IdOrganizacao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Usuarios_Ref_Organizacoes");

                    b.Navigation("Organizacao");
                });

            modelBuilder.Entity("PerfisAcessoPermissoes", b =>
                {
                    b.HasOne("FfkApi.Domain.Entities.PerfilAcesso", null)
                        .WithMany()
                        .HasForeignKey("IdPerfilAcesso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PerfisAcessoPermissoes_Ref_PerfisAcesso");

                    b.HasOne("FfkApi.Domain.Entities.Permissao", null)
                        .WithMany()
                        .HasForeignKey("IdPermissao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PerfisAcessoPermissoes_Ref_Permissoes");
                });

            modelBuilder.Entity("UsuariosPerfisAcesso", b =>
                {
                    b.HasOne("FfkApi.Domain.Entities.PerfilAcesso", null)
                        .WithMany()
                        .HasForeignKey("IdPerfilAcesso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UsuariosPerfisAcesso_Ref_PerfisAcesso");

                    b.HasOne("FfkApi.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UsuariosPerfisAcesso_Ref_Usuarios");
                });

            modelBuilder.Entity("UsuariosPermissoes", b =>
                {
                    b.HasOne("FfkApi.Domain.Entities.Permissao", null)
                        .WithMany()
                        .HasForeignKey("IdPermissao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UsuariosPermissoes_Ref_Permissoes");

                    b.HasOne("FfkApi.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UsuariosPermissoes_Ref_Usuarios");
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.Checklist", b =>
                {
                    b.Navigation("ChecklistItens");
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.ChecklistItem", b =>
                {
                    b.Navigation("ChecklistRespostasPossiveis");

                    b.Navigation("GatilhosDeResposta");
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.ChecklistPreenchido", b =>
                {
                    b.Navigation("ChecklistPreenchidoItens");
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.Equipe", b =>
                {
                    b.Navigation("Fila");

                    b.Navigation("Membros");
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.Fila", b =>
                {
                    b.Navigation("FilaItens");
                });

            modelBuilder.Entity("FfkApi.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Fila");
                });
#pragma warning restore 612, 618
        }
    }
}
